### ISSUE TITLE
Bug: panic when creating or dropping table.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend-client#37]
When creating a non-existed table or dropping an existed table, the client will panic.

Howerever, the creating/dropping is successful

```
> CREATE TABLE t1(a FLOAT, b INTEGER);
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', $HOME/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/arrow-flight-36.0.0/src/sql/client.rs:194:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

> DROP TABLE t1;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', $HOME/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/arrow-flight-36.0.0/src/sql/client.rs:194:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sundy-li** [comment]
Update is supported in databend latest version now.
